site_name: Preacher's Docs
site_url: https://preach-notes.com
nav:
    - Home: index.md
    - Selenium: selenium.md
    - Git: git.md
    - About: about.md
theme:
    name: windmill-dark
    custom_dir: custom_theme