site_name: Preacher's Docs
site_url: https://preach-notes.com

nav:
    - Home: index.md
    - About: about.md
    - Testing:
        - Playwright: playwright.md
        - Selenium: selenium.md
        - API Testing: api-testing.md
    - Tools:
        - Git: git.md
        - AI Tools: ai-tools.md

theme:
    name: material
    palette:
        scheme: slate
        primary: black
        accent: light green
    features:
        - navigation.sections
        - navigation.top
        - content.code.copy

extra_css:
    - css/custom.css

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - tables